export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_BUN = 'SET_BUN';
export const REMOVE_BUN = 'REMOVE_BUN';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT'



