export const URL_API = 'https://norma.nomoreparties.space/api/'
export const INGREDIENTS_END_POINT = 'ingredients';
export const ORDERS_END_POINT = 'orders';
export const PASSWORD_RESET = 'password-reset';
export const NEW_PASSWORD = 'password-reset/reset';
export const LOGIN_END_POINT = 'auth/login';
export const REGISTRATION_END_POINT = 'auth/register';
export const LOGOUT_END_POINT = 'auth/logout';
export const TOKEN_END_POINT = 'auth/token';
export const USER_END_POINT = 'auth/user';
export const WEB_SOCKET_ALL_ORDERS = 'wss://norma.nomoreparties.space/orders/all';
export const WEB_SOCKET_PROFILE_ORDERS = 'wss://norma.nomoreparties.space/orders';
export const URL_ORDERS = 'https://norma.nomoreparties.space/api/orders';

export const commonErrorMessage = 'Во время запроса произошла ошибка. Подождите немного и попробуйте ещё раз';
export const tokenError = 'Неверный код'
export const authErrorMessage = 'Вы ввели неправильный логин или пароль.';
export const conflictingEmailMessage = 'Пользователь с таким email уже существует.';
export const registrationErrorMessage = 'При регистрации пользователя произошла ошибка.';
export const profileUpdateErrorMessage = 'При обновлении профиля произошла ошибка.';
